adj1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
adj2 = input("Enter an adjective: ")
verb1 = input("Enter an verb: ")
adj3 = input("Enter an adjective: ")

print(f"Today I went to {adj1} zoo.")
print(f"In an exhibit, I saw a {noun1}")
print(f"{noun1} was {adj2} and {verb1}")
print(f"I was {adj3}!")